### ISSUE TITLE
Bug: `triton_ui.py` broken after ModelConfig change in #56

### ISSUE THREAD

**Issue by sandlbn** [meta-pytorch/KernelAgent#64]
### 🐛 Describe the bug

PR #56 changed `ModelConfig.provider_class` to `ModelConfig.provider_classes` (list), but `scripts/triton_ui.py` wasn't updated.

## Error

```
AttributeError: 'ModelConfig' object has no attribute 'provider_class'
```

## Location

`scripts/triton_ui.py` line 75

## Fix

```python
# Before:
self._model_to_provider = {
    cfg.name: cfg.provider_class for cfg in get_available_models()
}

# After:
self._model_to_provider = {
    cfg.name: cfg.provider_classes[0] for cfg in get_available_models()
}
```

### Platform and Version

main branch
